# Generated by Django 3.2.7 on 2021-11-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_os_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='type',
        ),
    ]
