# Generated by Django 3.2.7 on 2021-11-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_ram_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comps',
            name='RAM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ram'),
        ),
        migrations.AlterField(
            model_name='comps',
            name='CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cpu'),
        ),
    ]
